version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: psicologi_db
      POSTGRES_USER: psicologi_user
      POSTGRES_PASSWORD: psicologi_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=atipica
      - DB_USER=atipica_user
      - DB_PASSWORD=1qWNWFYJ20NDzIznlLF7ycvGN8ipfkMn
      - DB_HOST=dpg-d5v5oavfte5s73cg80kg-a
      - DB_PORT=5432

volumes:
  postgres_data:
