# Generated by Django 5.2.5 on 2026-02-08 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuityFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('specializzazione', models.CharField(blank=True, max_length=255, null=True)),
                ('partita_iva', models.CharField(blank=True, max_length=20, null=True)),
                ('esperienza_anni', models.PositiveIntegerField(default=0)),
                ('giorno_disponibile', models.CharField(blank=True, max_length=255, null=True)),
                ('orario_disponibile', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Psicologo',
                'verbose_name_plural': 'Psicologi',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='StripeFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=50, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Numero di telefono')),
                ('eta', models.PositiveIntegerField(verbose_name='Età')),
                ('emergenza', models.BooleanField(default=False, verbose_name='Sei in pericolo?')),
                ('rappresentante', models.CharField(blank=True, max_length=100, verbose_name='Per chi stai compilando questo questionario?')),
                ('preferenza_psicologo', models.CharField(blank=True, choices=[('Maschio', 'Maschio'), ('Femmina', 'Femmina'), ('Indifferente', 'Indifferente')], max_length=100, verbose_name='Da quale psicologo vorresti essere seguito?')),
                ('sintomi', models.TextField(verbose_name='Sintomi psicologici')),
                ('ambito', models.CharField(max_length=100, verbose_name='Ambito del problema')),
                ('motivo', models.TextField(verbose_name='Motivo per iniziare un percorso psicologico')),
                ('giorno_disponibile', models.CharField(blank=True, max_length=255, null=True)),
                ('orario_disponibile', models.CharField(blank=True, max_length=255, null=True)),
                ('terapia_gruppo', models.BooleanField(default=False, verbose_name='Interessato a un percorso di gruppo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paziente', to='core.psicologo')),
            ],
            options={
                'verbose_name': 'Paziente',
                'verbose_name_plural': 'Pazienti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Seduta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data seduta')),
                ('tipo_seduta', models.CharField(max_length=100, verbose_name='Tipo seduta')),
                ('avvenuta', models.BooleanField(default=False, verbose_name='Seduta avvenuta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedute', to='core.paziente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedute', to='core.psicologo')),
            ],
            options={
                'verbose_name': 'Seduta',
                'verbose_name_plural': 'Sedute',
                'ordering': ['data'],
            },
        ),
    ]
