# Generated by Django 5.2.5 on 2026-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acuityformresponse_psicologo_stripeformresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuityformresponse',
            name='headers',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripeformresponse',
            name='headers',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeformresponse',
            name='headers',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
