# Generated by Django 5.2.5 on 2025-09-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('specializzazioni', models.CharField(blank=True, max_length=255, null=True)),
                ('partita_iva', models.CharField(blank=True, max_length=20, null=True)),
                ('esperienza_anni', models.PositiveIntegerField(default=0)),
                ('disponibilita', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Psicologo',
                'verbose_name_plural': 'Psicologi',
                'ordering': ['cognome', 'nome'],
            },
        ),
    ]
