# Generated by Django 5.2.5 on 2025-09-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='disponibilita',
        ),
        migrations.AddField(
            model_name='psicologo',
            name='giorno_disponibile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='orario_disponibile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
