# Generated by Django 5.2.5 on 2025-09-27 14:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0002_remove_psicologo_disponibilita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='giorno_disponibile',
            field=models.CharField(blank=True, choices=[('LUN', 'Lunedì'), ('MAR', 'Martedì'), ('MER', 'Mercoledì'), ('GIO', 'Giovedì'), ('VEN', 'Venerdì'), ('SAB', 'Sabato'), ('DOM', 'Domenica')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='specializzazioni',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CLINICO', 'Psicologia Clinica'), ('COGNITIVO', 'Psicologia Cognitivo-Comportamentale'), ('SCOLASTICO', 'Psicologia Scolastica'), ('DELLA_SALUTE', 'Psicologia della Salute'), ('DEL_LAVORO', 'Psicologia del Lavoro e delle Organizzazioni'), ('NEUROPSICOLOGIA', 'Neuropsicologia'), ('SPORTIVO', 'Psicologia dello Sport'), ('CRIMINOLOGICO', 'Psicologia Criminale'), ('FORNENSE', 'Psicologia Forense'), ('INFANTILE', 'Psicologia Infantile'), ('SOCIALE', 'Psicologia Sociale'), ('RIABILITATIVA', 'Psicologia Riabilitativa')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
