# Generated by Django 5.2.5 on 2025-09-27 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0003_alter_psicologo_giorno_disponibile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='giorno_disponibile',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LUN', 'Lunedì'), ('MAR', 'Martedì'), ('MER', 'Mercoledì'), ('GIO', 'Giovedì'), ('VEN', 'Venerdì'), ('SAB', 'Sabato'), ('DOM', 'Domenica')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
