# Generated by Django 5.2.5 on 2025-09-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0004_alter_psicologo_giorno_disponibile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='specializzazioni',
        ),
        migrations.AddField(
            model_name='psicologo',
            name='specializzazione',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='giorno_disponibile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
