# Generated by Django 5.2.5 on 2025-09-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0005_remove_psicologo_specializzazioni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=50, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Numero di telefono')),
                ('eta', models.PositiveIntegerField(verbose_name='Età')),
                ('emergenza', models.BooleanField(default=False, verbose_name='Sei in pericolo?')),
                ('rappresentante', models.CharField(blank=True, max_length=100, verbose_name='Per chi stai compilando questo questionario?')),
                ('preferenza_psicologo', models.CharField(blank=True, choices=[('Maschio', 'Maschio'), ('Femmina', 'Femmina'), ('Indifferente', 'Indifferente')], max_length=100, verbose_name='Da quale psicologo vorresti essere seguito?')),
                ('sintomi', models.TextField(verbose_name='Sintomi psicologici')),
                ('ambito', models.CharField(max_length=100, verbose_name='Ambito del problema')),
                ('motivo', models.TextField(verbose_name='Motivo per iniziare un percorso psicologico')),
                ('giorno_disponibile', models.CharField(blank=True, max_length=255, null=True)),
                ('orario_disponibile', models.CharField(blank=True, max_length=255, null=True)),
                ('terapia_gruppo', models.BooleanField(default=False, verbose_name='Interessato a un percorso di gruppo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
