# Generated by Django 5.2.5 on 2025-09-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0006_paziente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paziente',
            options={'ordering': ['cognome', 'nome'], 'verbose_name': 'Paziente', 'verbose_name_plural': 'Pazienti'},
        ),
    ]
