# Generated by Django 5.2.5 on 2025-09-27 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0007_alter_paziente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paziente',
            name='psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paziente', to='pd.psicologo'),
        ),
    ]
