# Generated by Django 5.2.5 on 2025-09-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0008_paziente_psicologo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seduta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data seduta')),
                ('tipo_seduta', models.CharField(max_length=100, verbose_name='Tipo seduta')),
                ('avvenuta', models.BooleanField(default=False, verbose_name='Seduta avvenuta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedute', to='pd.paziente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedute', to='pd.psicologo')),
            ],
        ),
    ]
