# Generated by Django 5.2.5 on 2025-09-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0009_seduta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seduta',
            options={'ordering': ['data'], 'verbose_name': 'Seduta', 'verbose_name_plural': 'Sedute'},
        ),
    ]
