# Generated by Django 5.2.5 on 2026-02-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pd', '0010_alter_seduta_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seduta',
            name='paziente',
        ),
        migrations.RemoveField(
            model_name='seduta',
            name='psicologo',
        ),
        migrations.DeleteModel(
            name='Paziente',
        ),
        migrations.DeleteModel(
            name='Psicologo',
        ),
        migrations.DeleteModel(
            name='Seduta',
        ),
    ]
